//
// config.hpp
//
// Author: 	Lutz Bichler
//
// This file is part of the BMW Some/IP implementation.
//
// Copyright © 2013, 2014 Bayerische Motoren Werke AG (BMW).
// All rights reserved.
//

#ifndef VSOMEIP_SERVICE_DISCOVERY_CONFIG_HPP
#define VSOMEIP_SERVICE_DISCOVERY_CONFIG_HPP

#define VSOMEIP_DEFAULT_DEAMON_SERVICE_DISCOVERY_ENABLED true
#define VSOMEIP_DEFAULT_DEAMON_VIRTUAL_MODE_ENABLED false
#define VSOMEIP_DEFAULT_DEAMON_REGISTRY_PATH "/tmp/vsomeipd"

#define VSOMEIP_DEFAULT_SERVICE_DISCOVERY_PORT 30490
#define VSOMEIP_DEFAULT_SERVICE_DISCOVERY_MIN_INITIAL_DELAY 10
#define VSOMEIP_DEFAULT_SERVICE_DISCOVERY_MAX_INITIAL_DELAY 50
#define VSOMEIP_DEFAULT_SERVICE_DISCOVERY_REPETITION_BASE_DELAY 100
#define VSOMEIP_DEFAULT_SERVICE_DISCOVERY_REPETITION_MAX 5
#define VSOMEIP_DEFAULT_SERVICE_DISCOVERY_TIME_TO_LIVE 0xFFFFFFFF
#define VSOMEIP_DEFAULT_SERVICE_DISCOVERY_CYCLIC_OFFER_DELAY 2000
#define VSOMEIP_DEFAULT_SERVICE_DISCOVERY_CYCLIC_REQUEST_DELAY 2000
#define VSOMEIP_DEFAULT_SERVICE_DISCOVERY_REQUEST_RESPONSE_DELAY 2000

#endif // VSOMEIP_SERVICE_DISCOVERY_CONFIG_HPP
