# CMake generated Testfile for 
# Source directory: /home/kali/projects/vsomeip/test
# Build directory: /home/kali/projects/vsomeip/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(configuration-test "/home/kali/projects/vsomeip/test/configuration-test")
set_tests_properties(configuration-test PROPERTIES  _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3239;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(application_test "/home/kali/projects/vsomeip/test/application_test_starter.sh")
set_tests_properties(application_test PROPERTIES  TIMEOUT "80" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3244;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(application_test_single_process "/home/kali/projects/vsomeip/test/application_test_single_process_starter.sh")
set_tests_properties(application_test_single_process PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3248;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(application_test_availability "/home/kali/projects/vsomeip/test/application_test_availability_starter.sh")
set_tests_properties(application_test_availability PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3253;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(magic_cookies_test "/home/kali/projects/vsomeip/test/magic_cookies_test_starter.sh")
set_tests_properties(magic_cookies_test PROPERTIES  TIMEOUT "250" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3259;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(header_factory_test "/home/kali/projects/vsomeip/test/header_factory_test")
set_tests_properties(header_factory_test PROPERTIES  _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3265;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(header_factory_test_send_receive "/home/kali/projects/vsomeip/test/header_factory_test_send_receive_starter.sh")
set_tests_properties(header_factory_test_send_receive PROPERTIES  _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3266;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(local_routing_test "/home/kali/projects/vsomeip/test/local_routing_test_starter.sh")
set_tests_properties(local_routing_test PROPERTIES  _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3271;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(external_local_routing_test "/home/kali/projects/vsomeip/test/external_local_routing_test_starter.sh")
set_tests_properties(external_local_routing_test PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3275;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(local_payload_test "/home/kali/projects/vsomeip/test/local_payload_test_starter.sh")
set_tests_properties(local_payload_test PROPERTIES  _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3281;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(local_payload_test_huge_payload "/home/kali/projects/vsomeip/test/local_payload_test_huge_payload_starter.sh")
set_tests_properties(local_payload_test_huge_payload PROPERTIES  TIMEOUT "960" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3284;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(external_local_payload_test_client_local "/home/kali/projects/vsomeip/test/external_local_payload_test_client_local_starter.sh")
set_tests_properties(external_local_payload_test_client_local PROPERTIES  _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3288;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(external_local_payload_test_client_external "/home/kali/projects/vsomeip/test/external_local_payload_test_client_external_starter.sh")
set_tests_properties(external_local_payload_test_client_external PROPERTIES  TIMEOUT "480" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3291;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(external_local_payload_test_client_local_and_external "/home/kali/projects/vsomeip/test/external_local_payload_test_client_local_and_external_starter.sh")
set_tests_properties(external_local_payload_test_client_local_and_external PROPERTIES  _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3295;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(big_payload_test_local "/home/kali/projects/vsomeip/test/big_payload_test_local_starter.sh")
set_tests_properties(big_payload_test_local PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3301;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(big_payload_test_local_random "/home/kali/projects/vsomeip/test/big_payload_test_local_starter.sh" "RANDOM")
set_tests_properties(big_payload_test_local_random PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3306;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(big_payload_test_local_limited "/home/kali/projects/vsomeip/test/big_payload_test_local_starter.sh" "LIMITED")
set_tests_properties(big_payload_test_local_limited PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3311;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(big_payload_test_external "/home/kali/projects/vsomeip/test/big_payload_test_external_starter.sh")
set_tests_properties(big_payload_test_external PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3316;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(big_payload_test_external_random "/home/kali/projects/vsomeip/test/big_payload_test_external_starter.sh" "RANDOM")
set_tests_properties(big_payload_test_external_random PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3321;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(big_payload_test_external_limited "/home/kali/projects/vsomeip/test/big_payload_test_external_starter.sh" "LIMITED")
set_tests_properties(big_payload_test_external_limited PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3326;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(big_payload_test_external_limited_general "/home/kali/projects/vsomeip/test/big_payload_test_external_starter.sh" "LIMITEDGENERAL")
set_tests_properties(big_payload_test_external_limited_general PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3331;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(big_payload_test_local_queue_limited "/home/kali/projects/vsomeip/test/big_payload_test_local_starter.sh" "QUEUELIMITEDGENERAL")
set_tests_properties(big_payload_test_local_queue_limited PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3336;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(big_payload_test_external_queue_limited_general "/home/kali/projects/vsomeip/test/big_payload_test_external_starter.sh" "QUEUELIMITEDGENERAL")
set_tests_properties(big_payload_test_external_queue_limited_general PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3341;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(big_payload_test_external_queue_limited_specific "/home/kali/projects/vsomeip/test/big_payload_test_external_starter.sh" "QUEUELIMITEDSPECIFIC")
set_tests_properties(big_payload_test_external_queue_limited_specific PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3346;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(big_payload_test_external_udp "/home/kali/projects/vsomeip/test/big_payload_test_external_starter.sh" "UDP")
set_tests_properties(big_payload_test_external_udp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3351;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(client_id_test_diff_client_ids_diff_ports "/home/kali/projects/vsomeip/test/client_id_test_master_starter.sh" "client_id_test_diff_client_ids_diff_ports_master.json")
set_tests_properties(client_id_test_diff_client_ids_diff_ports PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3357;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(client_id_test_diff_client_ids_same_ports "/home/kali/projects/vsomeip/test/client_id_test_master_starter.sh" "client_id_test_diff_client_ids_same_ports_master.json")
set_tests_properties(client_id_test_diff_client_ids_same_ports PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3361;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(client_id_test_diff_client_ids_partial_same_ports "/home/kali/projects/vsomeip/test/client_id_test_master_starter.sh" "client_id_test_diff_client_ids_partial_same_ports_master.json")
set_tests_properties(client_id_test_diff_client_ids_partial_same_ports PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3365;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(client_id_test_utility "/home/kali/projects/vsomeip/test/client_id_test_utility")
set_tests_properties(client_id_test_utility PROPERTIES  ENVIRONMENT "VSOMEIP_CONFIGURATION=client_id_test_utility.json" TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3369;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(client_id_test_utility_masked_511 "/home/kali/projects/vsomeip/test/client_id_test_utility")
set_tests_properties(client_id_test_utility_masked_511 PROPERTIES  ENVIRONMENT "VSOMEIP_CONFIGURATION=client_id_test_utility_masked_511.json" TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3376;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(client_id_test_utility_masked_4095 "/home/kali/projects/vsomeip/test/client_id_test_utility")
set_tests_properties(client_id_test_utility_masked_4095 PROPERTIES  ENVIRONMENT "VSOMEIP_CONFIGURATION=client_id_test_utility_masked_4095.json" TIMEOUT "600" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3383;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(client_id_test_utility_masked_127 "/home/kali/projects/vsomeip/test/client_id_test_utility")
set_tests_properties(client_id_test_utility_masked_127 PROPERTIES  ENVIRONMENT "VSOMEIP_CONFIGURATION=client_id_test_utility_masked_127.json" TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3390;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(client_id_test_utility_discontinuous_masked_511 "/home/kali/projects/vsomeip/test/client_id_test_utility")
set_tests_properties(client_id_test_utility_discontinuous_masked_511 PROPERTIES  ENVIRONMENT "VSOMEIP_CONFIGURATION=client_id_test_utility_discontinuous_masked_511.json" TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3397;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(subscribe_notify_test_diff_client_ids_diff_ports_udp "/home/kali/projects/vsomeip/test/subscribe_notify_test_master_starter.sh" "UDP" "subscribe_notify_test_diff_client_ids_diff_ports_master_udp.json")
set_tests_properties(subscribe_notify_test_diff_client_ids_diff_ports_udp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3405;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(subscribe_notify_test_diff_client_ids_diff_ports_tcp "/home/kali/projects/vsomeip/test/subscribe_notify_test_master_starter.sh" "TCP" "subscribe_notify_test_diff_client_ids_diff_ports_master_tcp.json")
set_tests_properties(subscribe_notify_test_diff_client_ids_diff_ports_tcp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3409;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(subscribe_notify_test_diff_client_ids_diff_ports_both_tcp_and_udp "/home/kali/projects/vsomeip/test/subscribe_notify_test_master_starter.sh" "TCP_AND_UDP" "subscribe_notify_test_diff_client_ids_diff_ports_master.json")
set_tests_properties(subscribe_notify_test_diff_client_ids_diff_ports_both_tcp_and_udp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3413;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(subscribe_notify_test_diff_client_ids_same_ports_udp "/home/kali/projects/vsomeip/test/subscribe_notify_test_master_starter.sh" "UDP" "subscribe_notify_test_diff_client_ids_same_ports_master_udp.json")
set_tests_properties(subscribe_notify_test_diff_client_ids_same_ports_udp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3417;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(subscribe_notify_test_diff_client_ids_same_ports_tcp "/home/kali/projects/vsomeip/test/subscribe_notify_test_master_starter.sh" "TCP" "subscribe_notify_test_diff_client_ids_same_ports_master_tcp.json")
set_tests_properties(subscribe_notify_test_diff_client_ids_same_ports_tcp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3421;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(subscribe_notify_test_diff_client_ids_same_ports_both_tcp_and_udp "/home/kali/projects/vsomeip/test/subscribe_notify_test_master_starter.sh" "TCP_AND_UDP" "subscribe_notify_test_diff_client_ids_same_ports_master.json")
set_tests_properties(subscribe_notify_test_diff_client_ids_same_ports_both_tcp_and_udp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3425;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(subscribe_notify_test_diff_client_ids_partial_same_ports_both_tcp_and_udp "/home/kali/projects/vsomeip/test/subscribe_notify_test_master_starter.sh" "TCP_AND_UDP" "subscribe_notify_test_diff_client_ids_partial_same_ports_master.json")
set_tests_properties(subscribe_notify_test_diff_client_ids_partial_same_ports_both_tcp_and_udp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3429;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(subscribe_notify_test_diff_client_ids_diff_ports_same_service_id_udp "/home/kali/projects/vsomeip/test/subscribe_notify_test_master_starter.sh" "UDP" "subscribe_notify_test_diff_client_ids_diff_ports_same_service_id_master_udp.json" "SAME_SERVICE_ID")
set_tests_properties(subscribe_notify_test_diff_client_ids_diff_ports_same_service_id_udp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3433;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(subscribe_notify_test_diff_client_ids_diff_ports_autoconfig_udp "/home/kali/projects/vsomeip/test/subscribe_notify_test_master_starter.sh" "UDP" "subscribe_notify_test_diff_client_ids_diff_ports_autoconfig_master.json")
set_tests_properties(subscribe_notify_test_diff_client_ids_diff_ports_autoconfig_udp PROPERTIES  _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3437;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(subscribe_notify_test_one_event_two_eventgroups_udp "/home/kali/projects/vsomeip/test/subscribe_notify_test_one_event_two_eventgroups_master_starter.sh" "UDP" "subscribe_notify_test_one_event_two_eventgroups_master.json")
set_tests_properties(subscribe_notify_test_one_event_two_eventgroups_udp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3441;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(subscribe_notify_test_one_event_two_eventgroups_tcp "/home/kali/projects/vsomeip/test/subscribe_notify_test_one_event_two_eventgroups_master_starter.sh" "TCP" "subscribe_notify_test_one_event_two_eventgroups_master.json")
set_tests_properties(subscribe_notify_test_one_event_two_eventgroups_tcp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3445;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(subscribe_notify_one_test_diff_client_ids_diff_ports_udp "/home/kali/projects/vsomeip/test/subscribe_notify_one_test_master_starter.sh" "UDP" "subscribe_notify_one_test_diff_client_ids_diff_ports_master_udp.json")
set_tests_properties(subscribe_notify_one_test_diff_client_ids_diff_ports_udp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3450;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(subscribe_notify_one_test_diff_client_ids_diff_ports_tcp "/home/kali/projects/vsomeip/test/subscribe_notify_one_test_master_starter.sh" "TCP" "subscribe_notify_one_test_diff_client_ids_diff_ports_master_tcp.json")
set_tests_properties(subscribe_notify_one_test_diff_client_ids_diff_ports_tcp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3454;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(subscribe_notify_one_test_diff_client_ids_diff_ports_both_tcp_and_udp "/home/kali/projects/vsomeip/test/subscribe_notify_one_test_master_starter.sh" "TCP_AND_UDP" "subscribe_notify_one_test_diff_client_ids_diff_ports_master.json")
set_tests_properties(subscribe_notify_one_test_diff_client_ids_diff_ports_both_tcp_and_udp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3458;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(cpu_load_test "/home/kali/projects/vsomeip/test/cpu_load_test_master_starter.sh")
set_tests_properties(cpu_load_test PROPERTIES  TIMEOUT "3000" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3463;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(initial_event_test_diff_client_ids_diff_ports_udp "/home/kali/projects/vsomeip/test/initial_event_test_master_starter.sh" "initial_event_test_diff_client_ids_diff_ports_master_udp.json" "UDP")
set_tests_properties(initial_event_test_diff_client_ids_diff_ports_udp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3469;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(initial_event_test_diff_client_ids_diff_ports_tcp "/home/kali/projects/vsomeip/test/initial_event_test_master_starter.sh" "initial_event_test_diff_client_ids_diff_ports_master_tcp.json" "TCP")
set_tests_properties(initial_event_test_diff_client_ids_diff_ports_tcp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3473;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(initial_event_test_diff_client_ids_diff_ports_both_tcp_and_udp "/home/kali/projects/vsomeip/test/initial_event_test_master_starter.sh" "initial_event_test_diff_client_ids_diff_ports_master.json" "TCP_AND_UDP")
set_tests_properties(initial_event_test_diff_client_ids_diff_ports_both_tcp_and_udp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3477;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(initial_event_test_diff_client_ids_same_ports_udp "/home/kali/projects/vsomeip/test/initial_event_test_master_starter.sh" "initial_event_test_diff_client_ids_same_ports_master_udp.json" "UDP")
set_tests_properties(initial_event_test_diff_client_ids_same_ports_udp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3481;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(initial_event_test_diff_client_ids_same_ports_tcp "/home/kali/projects/vsomeip/test/initial_event_test_master_starter.sh" "initial_event_test_diff_client_ids_same_ports_master_tcp.json" "TCP")
set_tests_properties(initial_event_test_diff_client_ids_same_ports_tcp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3485;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(initial_event_test_diff_client_ids_same_ports_both_tcp_and_udp "/home/kali/projects/vsomeip/test/initial_event_test_master_starter.sh" "initial_event_test_diff_client_ids_same_ports_master.json" "TCP_AND_UDP")
set_tests_properties(initial_event_test_diff_client_ids_same_ports_both_tcp_and_udp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3489;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(initial_event_test_diff_client_ids_partial_same_ports_both_tcp_and_udp "/home/kali/projects/vsomeip/test/initial_event_test_master_starter.sh" "initial_event_test_diff_client_ids_partial_same_ports_master.json" "TCP_AND_UDP")
set_tests_properties(initial_event_test_diff_client_ids_partial_same_ports_both_tcp_and_udp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3493;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(initial_event_test_diff_client_ids_diff_ports_same_service_id_udp "/home/kali/projects/vsomeip/test/initial_event_test_master_starter.sh" "initial_event_test_diff_client_ids_diff_ports_same_service_id_master.json" "TCP_AND_UDP" "SAME_SERVICE_ID")
set_tests_properties(initial_event_test_diff_client_ids_diff_ports_same_service_id_udp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3497;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(initial_event_test_multiple_events_diff_client_ids_diff_ports_udp "/home/kali/projects/vsomeip/test/initial_event_test_master_starter.sh" "initial_event_test_diff_client_ids_diff_ports_master_udp.json" "UDP" "MULTIPLE_EVENTS")
set_tests_properties(initial_event_test_multiple_events_diff_client_ids_diff_ports_udp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3501;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(initial_event_test_multiple_events_diff_client_ids_diff_ports_tcp "/home/kali/projects/vsomeip/test/initial_event_test_master_starter.sh" "initial_event_test_diff_client_ids_diff_ports_master_tcp.json" "TCP" "MULTIPLE_EVENTS")
set_tests_properties(initial_event_test_multiple_events_diff_client_ids_diff_ports_tcp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3505;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(initial_event_test_multiple_events_diff_client_ids_diff_ports_both_tcp_and_udp "/home/kali/projects/vsomeip/test/initial_event_test_master_starter.sh" "initial_event_test_diff_client_ids_diff_ports_master.json" "TCP_AND_UDP" "MULTIPLE_EVENTS")
set_tests_properties(initial_event_test_multiple_events_diff_client_ids_diff_ports_both_tcp_and_udp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3509;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(initial_event_test_multiple_events_diff_client_ids_same_ports_udp "/home/kali/projects/vsomeip/test/initial_event_test_master_starter.sh" "initial_event_test_diff_client_ids_same_ports_master_udp.json" "UDP" "MULTIPLE_EVENTS")
set_tests_properties(initial_event_test_multiple_events_diff_client_ids_same_ports_udp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3513;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(initial_event_test_multiple_events_diff_client_ids_same_ports_tcp "/home/kali/projects/vsomeip/test/initial_event_test_master_starter.sh" "initial_event_test_diff_client_ids_same_ports_master_tcp.json" "TCP" "MULTIPLE_EVENTS")
set_tests_properties(initial_event_test_multiple_events_diff_client_ids_same_ports_tcp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3517;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(initial_event_test_multiple_events_diff_client_ids_same_ports_both_tcp_and_udp "/home/kali/projects/vsomeip/test/initial_event_test_master_starter.sh" "initial_event_test_diff_client_ids_same_ports_master.json" "TCP_AND_UDP" "MULTIPLE_EVENTS")
set_tests_properties(initial_event_test_multiple_events_diff_client_ids_same_ports_both_tcp_and_udp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3521;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(initial_event_test_multiple_events_diff_client_ids_partial_same_ports_both_tcp_and_udp "/home/kali/projects/vsomeip/test/initial_event_test_master_starter.sh" "initial_event_test_diff_client_ids_partial_same_ports_master.json" "TCP_AND_UDP" "MULTIPLE_EVENTS")
set_tests_properties(initial_event_test_multiple_events_diff_client_ids_partial_same_ports_both_tcp_and_udp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3525;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(initial_event_test_multiple_events_diff_client_ids_diff_ports_same_service_id_udp "/home/kali/projects/vsomeip/test/initial_event_test_master_starter.sh" "initial_event_test_diff_client_ids_diff_ports_same_service_id_master.json" "TCP_AND_UDP" "SAME_SERVICE_ID" "MULTIPLE_EVENTS")
set_tests_properties(initial_event_test_multiple_events_diff_client_ids_diff_ports_same_service_id_udp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3529;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(initial_event_test_multiple_events_subscribe_on_availability_diff_client_ids_diff_ports_udp "/home/kali/projects/vsomeip/test/initial_event_test_master_starter.sh" "initial_event_test_diff_client_ids_diff_ports_master_udp.json" "UDP" "MULTIPLE_EVENTS" "SUBSCRIBE_ON_AVAILABILITY")
set_tests_properties(initial_event_test_multiple_events_subscribe_on_availability_diff_client_ids_diff_ports_udp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3533;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(initial_event_test_multiple_events_subscribe_on_availability_diff_client_ids_diff_ports_tcp "/home/kali/projects/vsomeip/test/initial_event_test_master_starter.sh" "initial_event_test_diff_client_ids_diff_ports_master_tcp.json" "TCP" "MULTIPLE_EVENTS" "SUBSCRIBE_ON_AVAILABILITY")
set_tests_properties(initial_event_test_multiple_events_subscribe_on_availability_diff_client_ids_diff_ports_tcp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3537;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(initial_event_test_multiple_events_subscribe_on_availability_diff_client_ids_diff_ports_both_tcp_and_udp "/home/kali/projects/vsomeip/test/initial_event_test_master_starter.sh" "initial_event_test_diff_client_ids_diff_ports_master.json" "TCP_AND_UDP" "MULTIPLE_EVENTS" "SUBSCRIBE_ON_AVAILABILITY")
set_tests_properties(initial_event_test_multiple_events_subscribe_on_availability_diff_client_ids_diff_ports_both_tcp_and_udp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3541;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(initial_event_test_multiple_events_subscribe_on_availability_diff_client_ids_same_ports_udp "/home/kali/projects/vsomeip/test/initial_event_test_master_starter.sh" "initial_event_test_diff_client_ids_same_ports_master_udp.json" "UDP" "MULTIPLE_EVENTS" "SUBSCRIBE_ON_AVAILABILITY")
set_tests_properties(initial_event_test_multiple_events_subscribe_on_availability_diff_client_ids_same_ports_udp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3545;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(initial_event_test_multiple_events_subscribe_on_availability_diff_client_ids_same_ports_tcp "/home/kali/projects/vsomeip/test/initial_event_test_master_starter.sh" "initial_event_test_diff_client_ids_same_ports_master_tcp.json" "TCP" "MULTIPLE_EVENTS" "SUBSCRIBE_ON_AVAILABILITY")
set_tests_properties(initial_event_test_multiple_events_subscribe_on_availability_diff_client_ids_same_ports_tcp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3549;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(initial_event_test_multiple_events_subscribe_on_availability_diff_client_ids_same_ports_both_tcp_and_udp "/home/kali/projects/vsomeip/test/initial_event_test_master_starter.sh" "initial_event_test_diff_client_ids_same_ports_master.json" "TCP_AND_UDP" "MULTIPLE_EVENTS" "SUBSCRIBE_ON_AVAILABILITY")
set_tests_properties(initial_event_test_multiple_events_subscribe_on_availability_diff_client_ids_same_ports_both_tcp_and_udp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3553;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(initial_event_test_multiple_events_subscribe_on_availability_diff_client_ids_partial_same_ports_both_tcp_and_udp "/home/kali/projects/vsomeip/test/initial_event_test_master_starter.sh" "initial_event_test_diff_client_ids_partial_same_ports_master.json" "TCP_AND_UDP" "MULTIPLE_EVENTS" "SUBSCRIBE_ON_AVAILABILITY")
set_tests_properties(initial_event_test_multiple_events_subscribe_on_availability_diff_client_ids_partial_same_ports_both_tcp_and_udp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3557;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(initial_event_test_multiple_events_subscribe_on_availability_diff_client_ids_diff_ports_same_service_id_udp "/home/kali/projects/vsomeip/test/initial_event_test_master_starter.sh" "initial_event_test_diff_client_ids_diff_ports_same_service_id_master.json" "TCP_AND_UDP" "SAME_SERVICE_ID" "MULTIPLE_EVENTS" "SUBSCRIBE_ON_AVAILABILITY")
set_tests_properties(initial_event_test_multiple_events_subscribe_on_availability_diff_client_ids_diff_ports_same_service_id_udp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3561;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(initial_event_test_multiple_events_diff_client_ids_diff_ports_partial_subscription_udp "/home/kali/projects/vsomeip/test/initial_event_test_master_starter.sh" "initial_event_test_diff_client_ids_diff_ports_master_udp.json" "UDP" "MULTIPLE_EVENTS" "SUBSCRIBE_ONLY_ONE")
set_tests_properties(initial_event_test_multiple_events_diff_client_ids_diff_ports_partial_subscription_udp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3565;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(initial_event_test_multiple_events_diff_client_ids_diff_ports_partial_subscription_tcp "/home/kali/projects/vsomeip/test/initial_event_test_master_starter.sh" "initial_event_test_diff_client_ids_diff_ports_master_tcp.json" "TCP" "MULTIPLE_EVENTS" "SUBSCRIBE_ONLY_ONE")
set_tests_properties(initial_event_test_multiple_events_diff_client_ids_diff_ports_partial_subscription_tcp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3569;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(initial_event_test_multiple_events_diff_client_ids_diff_ports_partial_subscription_both_tcp_and_udp "/home/kali/projects/vsomeip/test/initial_event_test_master_starter.sh" "initial_event_test_diff_client_ids_diff_ports_master.json" "TCP_AND_UDP" "MULTIPLE_EVENTS" "SUBSCRIBE_ONLY_ONE")
set_tests_properties(initial_event_test_multiple_events_diff_client_ids_diff_ports_partial_subscription_both_tcp_and_udp PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3573;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(offer_test_local "/home/kali/projects/vsomeip/test/offer_test_local_starter.sh")
set_tests_properties(offer_test_local PROPERTIES  TIMEOUT "360" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3578;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(offer_test_external "/home/kali/projects/vsomeip/test/offer_test_external_master_starter.sh")
set_tests_properties(offer_test_external PROPERTIES  _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3581;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(offer_test_big_sd_msg "/home/kali/projects/vsomeip/test/offer_test_big_sd_msg_master_starter.sh")
set_tests_properties(offer_test_big_sd_msg PROPERTIES  TIMEOUT "360" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3584;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(offered_services_info_test_local "/home/kali/projects/vsomeip/test/offered_services_info_test_local_starter.sh")
set_tests_properties(offered_services_info_test_local PROPERTIES  TIMEOUT "180" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3589;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(restart_routing_test "/home/kali/projects/vsomeip/test/restart_routing_test_starter.sh")
set_tests_properties(restart_routing_test PROPERTIES  _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3594;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(pending_subscription_test_subscribe "/home/kali/projects/vsomeip/test/pending_subscription_test_master_starter.sh" "SUBSCRIBE")
set_tests_properties(pending_subscription_test_subscribe PROPERTIES  TIMEOUT "180" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3611;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(pending_subscription_test_alternating_subscribe_unsubscribe "/home/kali/projects/vsomeip/test/pending_subscription_test_master_starter.sh" "SUBSCRIBE_UNSUBSCRIBE")
set_tests_properties(pending_subscription_test_alternating_subscribe_unsubscribe PROPERTIES  TIMEOUT "180" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3615;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(pending_subscription_test_unsubscribe "/home/kali/projects/vsomeip/test/pending_subscription_test_master_starter.sh" "UNSUBSCRIBE")
set_tests_properties(pending_subscription_test_unsubscribe PROPERTIES  TIMEOUT "180" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3619;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(pending_subscription_test_alternating_subscribe_unsubscribe_nack "/home/kali/projects/vsomeip/test/pending_subscription_test_master_starter.sh" "SUBSCRIBE_UNSUBSCRIBE_NACK")
set_tests_properties(pending_subscription_test_alternating_subscribe_unsubscribe_nack PROPERTIES  TIMEOUT "180" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3623;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(pending_subscription_test_alternating_subscribe_unsubscribe_same_port "/home/kali/projects/vsomeip/test/pending_subscription_test_master_starter.sh" "SUBSCRIBE_UNSUBSCRIBE_SAME_PORT")
set_tests_properties(pending_subscription_test_alternating_subscribe_unsubscribe_same_port PROPERTIES  TIMEOUT "180" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3627;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(pending_subscription_test_subscribe_resubscribe_mixed "/home/kali/projects/vsomeip/test/pending_subscription_test_master_starter.sh" "SUBSCRIBE_RESUBSCRIBE_MIXED")
set_tests_properties(pending_subscription_test_subscribe_resubscribe_mixed PROPERTIES  TIMEOUT "180" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3631;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(pending_subscription_test_subscribe_stopsubscribe_subscribe "/home/kali/projects/vsomeip/test/pending_subscription_test_master_starter.sh" "SUBSCRIBE_STOPSUBSCRIBE_SUBSCRIBE")
set_tests_properties(pending_subscription_test_subscribe_stopsubscribe_subscribe PROPERTIES  TIMEOUT "180" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3635;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(pending_subscription_test_send_request_to_sd_port "/home/kali/projects/vsomeip/test/pending_subscription_test_master_starter.sh" "REQUEST_TO_SD")
set_tests_properties(pending_subscription_test_send_request_to_sd_port PROPERTIES  TIMEOUT "180" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3639;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(malicious_data_test_events "/home/kali/projects/vsomeip/test/malicious_data_test_master_starter.sh" "MALICIOUS_EVENTS")
set_tests_properties(malicious_data_test_events PROPERTIES  TIMEOUT "180" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3644;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(malicious_data_test_protocol_version "/home/kali/projects/vsomeip/test/malicious_data_test_master_starter.sh" "PROTOCOL_VERSION")
set_tests_properties(malicious_data_test_protocol_version PROPERTIES  TIMEOUT "180" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3648;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(malicious_data_test_message_type "/home/kali/projects/vsomeip/test/malicious_data_test_master_starter.sh" "MESSAGE_TYPE")
set_tests_properties(malicious_data_test_message_type PROPERTIES  TIMEOUT "180" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3652;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(malicious_data_test_return_code "/home/kali/projects/vsomeip/test/malicious_data_test_master_starter.sh" "RETURN_CODE")
set_tests_properties(malicious_data_test_return_code PROPERTIES  TIMEOUT "180" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3656;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(malicious_data_test_wrong_header_fields_udp "/home/kali/projects/vsomeip/test/malicious_data_test_master_starter.sh" "WRONG_HEADER_FIELDS_UDP")
set_tests_properties(malicious_data_test_wrong_header_fields_udp PROPERTIES  TIMEOUT "180" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3660;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(npdu_test_udp "/home/kali/projects/vsomeip/test/npdu_test_starter.sh" "UDP" "sync")
set_tests_properties(npdu_test_udp PROPERTIES  TIMEOUT "840" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3665;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(npdu_test_tcp "/home/kali/projects/vsomeip/test/npdu_test_starter.sh" "TCP" "sync")
set_tests_properties(npdu_test_tcp PROPERTIES  TIMEOUT "840" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3669;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(e2e_test_external "/home/kali/projects/vsomeip/test/e2e_test_external_master_start.sh" "e2e_test_client_external.json")
set_tests_properties(e2e_test_external PROPERTIES  TIMEOUT "180" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3674;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(event_test_payload_fixed_udp "/home/kali/projects/vsomeip/test/event_test_master_starter.sh" "PAYLOAD_FIXED" "UDP")
set_tests_properties(event_test_payload_fixed_udp PROPERTIES  TIMEOUT "180" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3685;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(event_test_payload_fixed_tcp "/home/kali/projects/vsomeip/test/event_test_master_starter.sh" "PAYLOAD_FIXED" "TCP")
set_tests_properties(event_test_payload_fixed_tcp PROPERTIES  TIMEOUT "180" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3689;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(event_test_payload_dynamic_udp "/home/kali/projects/vsomeip/test/event_test_master_starter.sh" "PAYLOAD_DYNAMIC" "UDP")
set_tests_properties(event_test_payload_dynamic_udp PROPERTIES  TIMEOUT "180" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3693;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(event_test_payload_dynamic_tcp "/home/kali/projects/vsomeip/test/event_test_master_starter.sh" "PAYLOAD_DYNAMIC" "TCP")
set_tests_properties(event_test_payload_dynamic_tcp PROPERTIES  TIMEOUT "180" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3697;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(someip_tp_test_in_sequence "/home/kali/projects/vsomeip/test/someip_tp_test_master_starter.sh" "IN_SEQUENCE")
set_tests_properties(someip_tp_test_in_sequence PROPERTIES  TIMEOUT "180" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3702;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(someip_tp_test_mixed "/home/kali/projects/vsomeip/test/someip_tp_test_master_starter.sh" "MIXED")
set_tests_properties(someip_tp_test_mixed PROPERTIES  TIMEOUT "180" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3706;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(someip_tp_test_incomplete "/home/kali/projects/vsomeip/test/someip_tp_test_master_starter.sh" "INCOMPLETE")
set_tests_properties(someip_tp_test_incomplete PROPERTIES  TIMEOUT "180" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3710;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(someip_tp_test_duplicate "/home/kali/projects/vsomeip/test/someip_tp_test_master_starter.sh" "DUPLICATE")
set_tests_properties(someip_tp_test_duplicate PROPERTIES  TIMEOUT "180" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3714;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(someip_tp_test_overlap "/home/kali/projects/vsomeip/test/someip_tp_test_master_starter.sh" "OVERLAP")
set_tests_properties(someip_tp_test_overlap PROPERTIES  TIMEOUT "180" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3718;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
add_test(someip_tp_test_overlap_front_back "/home/kali/projects/vsomeip/test/someip_tp_test_master_starter.sh" "OVERLAP_FRONT_BACK")
set_tests_properties(someip_tp_test_overlap_front_back PROPERTIES  TIMEOUT "180" _BACKTRACE_TRIPLES "/home/kali/projects/vsomeip/test/CMakeLists.txt;3722;add_test;/home/kali/projects/vsomeip/test/CMakeLists.txt;0;")
