@startuml

Actor Client as CLI

Actor Service as SRV

SRV -> CLI : Offer service

CLI -> SRV : Request service

CLI <- CLI : Start toggle

CLI -> SRV : Subscribe service

CLI <- CLI : Sleep 3 seconds

CLI <- CLI : Wakes up, Middle Toggle

CLI -> SRV : Unsubscribe service

SRV -> SRV : Sleep 3 seconds

CLI -> SRV : Subscribe service

note right
    Both client and service sleep for 3 seconds,
    but since client sleeps first, service will
    receive the next subscribe in a sleep state
end note

CLI <- CLI : Sleeps 2 seconds

CLI <- CLI : Wakes up, End Toggle

CLI -> SRV : Unsubscribe service

CLI -> SRV : Subscribe service

CLI -> SRV : Send suspend command

SRV -> SRV : Wakes up, processes subscribe and new unsubscribe and sleeps again

SRV -> SRV : Wakes up, processes subscribe and goes into suspend for 5 seconds

SRV -> SRV : Resumes

SRV -> CLI : Sending client initial events

CLI -> SRV : Sending service signal to stop

@enduml
