@startuml

Actor service_provider as SP

participant routing_manager as RM

SP -> RM : registration process

RM --\ SP : REGISTER_ACK

loop While test timer hasnt elapsed

  SP -> RM : STOP OFFER
  
  RM --\ SP : ON_UNAVAILABLE
  
  note right
    Service Provider will be waiting for the
    availability to trigger the next command
  end note

  SP -> RM : OFFER

  RM --\ SP : ON_AVAILABLE
  
  note right
    Service Provider will be waiting for the
    availability to trigger the next command
  end note
  
end

@enduml
