network:
  version: 2
  ethernets:
    enp0s3:  # Replace with your network interface name (check with `ip a`)
      addresses:
        - 192.168.10.1/24
      gateway4: 192.168.10.1  # Optional, adjust if a gateway is needed
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]
