@startuml

Actor Service_provider as SP

participant routing_manager as RM

participant Service_consumer as SC

SP -> RM : OFFER

SP -> SC : notify 0x8001

SP -> SC : notify 0x8002

alt If test mode has a remote client that is not allowed

  SP -> SP : sleep for 10s + 250ms * number\nof messages to send

  SP -> SP : stop
end

note across
  Wait for TEST_SERVICE_METHOD_ID_SHUTDOWN request
endnote

  SC --\ SP : REQUEST\nTEST_SERVICE_METHOD_ID_SHUTDOWN

  SP -> SP : stop

note across
  For every message received in background
endnote
  SC --\ SP : request

  SP -> SP : check serviceID and instanceID

  SP -> SC : response

  SP -> SP : number_of_received_messages_++

@enduml
