//
// config.hpp
//
// Author: 	Lutz Bichler
//
// This file is part of the BMW Some/IP implementation.
//
// Copyright 2013, 2024 Bayerische Motoren Werke AG (BMW).
// All rights reserved.
//

#include <vsomeip_internal/protocol.hpp>

#ifndef VSOMEIP_CONFIG_HPP
#define VSOMEIP_CONFIG_HPP

#define VSOMEIP_DEFAULT_CONFIGURATION_FILE_PATH	 "../vsomeip.conf"

#define VSOMEIP_MAX_TCP_MESSAGE_SIZE	4095
#define VSOMEIP_MAX_UDP_MESSAGE_SIZE	1446
#define VSOMEIP_MIN_ENDPOINT_SIZE		   6
#define VSOMEIP_MAX_ENDPOINT_SIZE		 131

#define VSOMEIP_DEFAULT_QUEUE_SIZE		(VSOMEIP_MAX_TCP_MESSAGE_SIZE \
										 + VSOMEIP_MAX_ENDPOINT_SIZE \
										 + VSOMEIP_PROTOCOL_OVERHEAD \
										 + VSOMEIP_PROTOCOL_RESERVED)

#define VSOMEIP_DEFAULT_CONNECT_TIMEOUT	1000
#define VSOMEIP_DEFAULT_FLUSH_TIMEOUT	1000
#define VSOMEIP_DEFAULT_RETRY_TIMEOUT	  20

#define VSOMEIP_DEFAULT_WATCHDOG_CYCLE	1000
#define VSOMEIP_DEFAULT_WATCHDOG_TIMEOUT 200
#define VSOMEIP_DEFAULT_MAX_MISSING_PONGS  3

#define VSOMEIP_ANY_SERVICE				0xFFFF
#define VSOMEIP_ANY_INSTANCE			0xFFFF
#define VSOMEIP_ANY_METHOD				0xFFFF

#define	VSOMEIP_MIN_MULTICAST			0xE0000000

#endif // VSOMEIP_CONFIG_HPP
