name: C/C++ CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout vsomeip repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Checkout build-files
        uses: actions/checkout@v4
        with:
          repository: qnx-ports/build-files
          path: build-files
          cache: true

      - name: Checkout boost
        uses: actions/checkout@v4
        with:
          repository: boostorg/boost
          path: boost
          ref: boost-1.78.0
          submodules: recursive
          cache: true
  
      - name: Checkout googletest
        uses: actions/checkout@v4
        with:
          repository: qnx-ports/googletest
          path: googletest
          ref: qnx_v1.13.0
          cache: true

